[package]
name = "crab-core"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tokio-util.workspace = true
axum.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
regex.workspace = true
fancy-regex.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
arc-swap.workspace = true
indexmap.workspace = true
chrono.workspace = true
flate2.workspace = true
md-5.workspace = true
sha1.workspace = true
sha2.workspace = true
hex.workspace = true
base32.workspace = true
encoding_rs.workspace = true
html-escape.workspace = true
urlencoding.workspace = true
url.workspace = true
uuid.workspace = true
async-trait.workspace = true
futures.workspace = true
tracing.workspace = true
anyhow.workspace = true
rand.workspace = true
