[package]
name = "crab-ops"
version.workspace = true
edition.workspace = true

[dependencies]
crab-core.workspace = true
tokio.workspace = true
tokio-util.workspace = true
axum.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
fancy-regex.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
indexmap.workspace = true
chrono.workspace = true
async-trait.workspace = true
futures.workspace = true
anyhow.workspace = true
urlencoding.workspace = true
url.workspace = true
rand.workspace = true
flate2.workspace = true
uuid.workspace = true

[dev-dependencies]
tower.workspace = true
